In [1]:
!pip install odfpy
import pandas as pd

Requirement already satisfied: odfpy in c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages (1.4.1)
Requirement already satisfied: defusedxml in c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages (from odfpy) (0.7.1)

WARNING: Ignoring invalid distribution - (c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (c:\users\robiul islam\anaconda3_new\envs\cudabasic\lib\site-packages)

In [2]:
df1 = pd.read_excel('ROC.ods')
df1.head()

,Precision,Recall,F1-Score,Specificity,Time,ROC AUC,Most Efficient Class,PreProcesstime,optimizers,signal_fiq,dataset
0,0.80,0.84,0.82,0.837104,12066.482950,0.826339,right hemiparesis,127.525830,adamax,theta,Necker cube
1,0.80,0.84,0.82,0.837104,12066.482950,0.826339,right hemiparesis,127.525830,adamax,theta,Necker cube
2,0.81,0.79,0.80,0.786290,15807.935710,0.784850,left hemiparesis,125.252710,nadam,theta,Necker cube
3,0.80,0.75,0.78,0.752174,3480.999766,0.784598,right hemiparesis,122.604216,Adagrad,theta,Necker cube
4,0.76,0.78,0.77,0.782979,10216.003830,0.763228,left hemiparesis,124.515174,Adam,theta,Necker cube

In [3]:
df2 = pd.read_excel('SHAP.ods')
df2.head()

,Top Feature,Top Feature Value,Time for Top Feature,SHAP Time,optimizers,signal_fiq,dataset
0,Feature 792,-7.385430,3.168,1167.255153,nadam,alpha,Mona Lisa
1,Feature 1051,-3.631186,4.204,1163.934246,nadam,beta,Necker cube
2,Feature 7992,8.323581,31.968,1112.960799,nadam,alpha,Necker cube
3,Feature 1466,0.034067,5.864,1107.847206,nadam,theta,Necker cube
4,Feature 14222,1.849844,56.888,1111.133432,nadam,theta,Mona Lisa

In [4]:
merged_df = pd.merge(df1, df2, on=['optimizers', 'signal_fiq', 'dataset'], how='outer')
merged_df.to_excel('merged_sheet.ods', index=False)

In [5]:
merged_df

,Precision,Recall,F1-Score,Specificity,Time,ROC AUC,Most Efficient Class,PreProcesstime,optimizers,signal_fiq,dataset,Top Feature,Top Feature Value,Time for Top Feature,SHAP Time
0,0.80,0.84,0.82,0.837104,12066.482950,0.826339,right hemiparesis,127.525830,adamax,theta,Necker cube,Feature 930,-3.242497,3.720,1109.400125
1,0.80,0.84,0.82,0.837104,12066.482950,0.826339,right hemiparesis,127.525830,adamax,theta,Necker cube,Feature 930,-3.242497,3.720,1109.400125
2,0.81,0.79,0.80,0.786290,15807.935710,0.784850,left hemiparesis,125.252710,nadam,theta,Necker cube,Feature 1466,0.034067,5.864,1107.847206
3,0.80,0.75,0.78,0.752174,3480.999766,0.784598,right hemiparesis,122.604216,Adagrad,theta,Necker cube,Feature 7494,-1240.172071,29.976,1105.165402
4,0.76,0.78,0.77,0.782979,10216.003830,0.763228,left hemiparesis,124.515174,Adam,theta,Necker cube,Feature 5206,-2.997411,20.824,1105.442082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,0.73,0.71,0.72,0.707424,16419.175170,0.728712,right hemiparesis,123.217430,adadelta,alpha,Mona Lisa,Feature 921,0.581554,3.684,1112.306984
85,0.51,1.00,0.68,1.000000,8981.571735,0.500000,left hemiparesis,319.863012,FTRL,alpha,Mona Lisa,NaN,NaN,NaN,NaN
86,0.60,0.63,0.62,0.628205,1577.878313,0.606310,left hemiparesis,126.123437,SGD,alpha,Mona Lisa,Feature 862,10.131962,3.448,1111.731339
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adam,gamma,Mona Lisa,Feature 799,-4.788555,3.196,1109.317472
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adam,beta,Mona Lisa,Feature 1098,-0.741204,4.392,1107.917643

In [7]:
sorted_df = merged_df.sort_values(by='dataset', ascending=False)
sorted_df

,Precision,Recall,F1-Score,Specificity,Time,ROC AUC,Most Efficient Class,PreProcesstime,optimizers,signal_fiq,dataset,Top Feature,Top Feature Value,Time for Top Feature,SHAP Time
0,0.80,0.84,0.82,0.837104,12066.482950,0.826339,right hemiparesis,127.525830,adamax,theta,Necker cube,Feature 930,-3.242497,3.720,1109.400125
40,0.73,0.74,0.74,0.737705,11770.335950,0.721794,left hemiparesis,127.681489,Adam,delta,Necker cube,Feature 1125,14.924017,4.500,1174.540704
75,0.73,0.71,0.72,0.712000,16410.569400,0.704837,left hemiparesis,125.275219,adadelta,alpha,Necker cube,Feature 1002,3.695127,4.008,1108.762511
73,0.75,0.83,0.79,0.832618,15421.968210,0.774068,left hemiparesis,124.715788,nadam,alpha,Necker cube,Feature 7992,8.323581,31.968,1112.960799
72,0.75,0.83,0.79,0.830435,9156.973560,0.779047,left hemiparesis,127.397074,RMSprop,alpha,Necker cube,Feature 996,-0.713455,3.984,1109.849651
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,0.77,0.74,0.76,0.742857,15694.608610,0.746429,left hemiparesis,125.656082,nadam,delta,Mona Lisa,Feature 1593,-0.892431,6.372,1108.672936
48,0.73,0.78,0.75,0.779661,8601.442986,0.741359,left hemiparesis,124.798707,Adam,delta,Mona Lisa,Feature 4098,10.116467,16.392,1105.744721
49,0.71,0.75,0.73,0.751092,9263.042257,0.727241,left hemiparesis,123.395855,RMSprop,delta,Mona Lisa,Feature 776,18.632519,3.104,1108.278204
50,0.71,0.64,0.67,0.644898,1482.552550,0.672449,left hemiparesis,121.636686,SGD,delta,Mona Lisa,Feature 1565,-33.840354,6.260,1107.381469
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adam,beta,Mona Lisa,Feature 1098,-0.741204,4.392,1107.917643

In [8]:
sorted_df = merged_df.sort_values(by='optimizers', ascending=False)
sorted_df

,Precision,Recall,F1-Score,Specificity,Time,ROC AUC,Most Efficient Class,PreProcesstime,optimizers,signal_fiq,dataset,Top Feature,Top Feature Value,Time for Top Feature,SHAP Time
22,0.89,0.88,0.88,0.875519,9357.950413,0.877491,left hemiparesis,121.146584,nadam,gamma,Necker cube,Feature 6509,-0.723496,26.036,1105.809683
2,0.81,0.79,0.80,0.786290,15807.935710,0.784850,left hemiparesis,125.252710,nadam,theta,Necker cube,Feature 1466,0.034067,5.864,1107.847206
83,0.72,0.81,0.76,0.806306,15534.801130,0.763235,left hemiparesis,126.171476,nadam,alpha,Mona Lisa,Feature 792,-7.385430,3.168,1167.255153
30,0.84,0.92,0.88,0.919149,14671.786160,0.872618,left hemiparesis,122.150515,nadam,gamma,Mona Lisa,NaN,NaN,NaN,NaN
73,0.75,0.83,0.79,0.832618,15421.968210,0.774068,left hemiparesis,124.715788,nadam,alpha,Necker cube,Feature 7992,8.323581,31.968,1112.960799
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,0.80,0.75,0.78,0.752174,3480.999766,0.784598,right hemiparesis,122.604216,Adagrad,theta,Necker cube,Feature 7494,-1240.172071,29.976,1105.165402
37,0.78,0.82,0.80,0.824268,5061.869129,0.792665,left hemiparesis,123.071470,Adagrad,delta,Necker cube,Feature 9935,120.614252,39.740,1113.357374
31,0.88,0.87,0.87,0.865217,3900.136877,0.877290,right hemiparesis,123.608473,Adagrad,gamma,Mona Lisa,Feature 917,-0.211653,3.668,1128.072093
21,0.87,0.91,0.89,0.905172,5092.515796,0.886063,left hemiparesis,124.846867,Adagrad,gamma,Necker cube,Feature 838,-3.572418,3.352,1115.817009
56,0.90,0.86,0.88,0.861660,6604.581390,0.871868,left hemiparesis,125.226659,Adagrad,beta,Necker cube,Feature 956,16.365261,3.824,1107.496627

In [9]:
sorted_df.to_excel('sort.ods', index=False)